

title: clvi.eu
email: contact@clvi.eu
description: >- # this means to ignore newlines until "baseurl:"
  Claire Villard's personal website. Find here my resume and some personal projects I wrote.
baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
name: Claire Villard


defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

